src/base-components/Form/FormInput.vue
src/components/CommonInput.vue
src/components/Crud.vue
src/components/ScheduleFieldset.vue
src/composables/alerts.ts
src/composables/isRole.ts
src/composables/useProvider.ts
src/pages/chronogram/Form.vue
src/pages/chronogram/Index.vue
src/pages/forms/FormEdit.vue
src/pages/forms/first_form.vue
src/router/index.ts

PR que corrige bugs en la creación y listado de Beneficiarios y Cronogramas - modifique la opción isRole para las pantallas de listas y agregué un emit change en el formInput para usar el evento @change en CommonInput

Cronogramas-Beneficiarios Fixed

---

src/components/Crud.vue
src/pages/coordinators/FormEdit.vue
src/pages/methodologist/Edit.vue
src/pages/methodologist/Form.vue
src/pages/methodologist/Index.vue
src/pages/subdirector/review/methodologist/Form.vue
src/pages/subdirector/review/methodologist/Index.vue
src/pages/subdirector/visit/Form.vue
src/pages/subdirector/visit/Index.vue
src/router/index.ts
src/services/methodologistVisitServices.ts
src/stores/side-menu.ts

- Crea y visualiza las visitas (Back no hace update)
- El subdirector puede visualizar visitas de metodologos (Back no hace revisiones)

Metodologo

---

src/components/Crud.vue
src/pages/administrative_director/reviews/directorVisit/Index.vue
src/pages/administrative_director/reviews/directorVisit/VisitReview.vue
src/pages/psychosocial/custom-visit/Index.vue
src/pages/psychosocial/visit/Index.vue
src/pages/psychosocial_coordinator/reviews/customVisit/CustomVisitReview.vue
src/pages/psychosocial_coordinator/reviews/visit/Index.vue
src/pages/psychosocial_coordinator/reviews/visit/visitReview.vue
src/pages/technical_director/visits/FormEdit.vue
src/stores/side-menu.ts

Conexión Visitas Director tecnico (Creación, edición, visualización y edición) V2 (Para test), organizacion del side-menu y modificación de variables en algunas paginas para el modal (no afecta funcionamiento)

Juan chicue

---

src/components/Crud.vue
src/pages/coordinators/Form.vue
src/pages/coordinators/FormEdit.vue
src/pages/coordinators/Index.vue
src/pages/methodologist/Edit.vue
src/pages/methodologist/Form.vue
src/pages/methodologist/Index.vue
src/pages/subdirector/review/coordinator/Form.vue
src/pages/subdirector/review/coordinator/Index.vue
src/pages/subdirector/review/methodologist/Form.vue
src/pages/subdirector/review/methodologist/Index.vue
src/pages/subdirector/visit/Edit.vue
src/pages/subdirector/visit/Form.vue
src/pages/subdirector/visit/Index.vue
src/pages/technical_director/reviews/subdirectorVisitReview.vue
src/router/index.ts
src/stores/side-menu.ts

- Se trae las disciplinas de un monitor en especifico
- Ya no permite ingrese sin que tenga iniciada la sesion

Disciplinas monitores

---

src/stores/side-menu.ts

Se cambio el nombre de semilleros a monitor, se elimino del menu usuarios y beneficiarios

Cambio side menu

---

src/pages/chronogram/Form.vue

No permite añadir mas horarios si se escoge al grupo 5

End ticket SSIS-167

---

src/pages/chronogram/Form.vue

- Permite clonar cronogramas pasados

End ticket SSIS-169

---

src/pages/chronogram/Form.vue

No permite crear cronogramas sin horarios

END Ticket SSIS-180

---

src/pages/chronogram/Form.vue

Se quito la obligatoriedad de observaciones

END Ticket SSIS-186

---

src/components/Crud.vue
src/pages/user/FormEdit.vue
src/router/index.ts
src/services/userServices.ts

Ahora al cargar la vista de editar usuario, precarga correctamente varios componentes
Se ha creado la función para cambiar el estado del usuario e inactivarlo

preload edit user and button toggleUserStatus for users

---

src/components/Crud.vue
src/pages/user/FormEdit.vue

Se ha modificado el botón de activar e inactivar usaurio para que funcione con un checkbox

SSIS-181 boton activar e inactivar usaurios

---

src/pages/forms/first_form.vue
src/pages/user/Index.vue

el error reportado es que no mostraba alerta cuando el documento era duplicado, pero se detecto que a nivel general no mostraba alerta en las validaciones al crear el beneficiario

 SIS187 mostrar errores al crear beneficiaro

---

src/components/Crud.vue

Al editar si es rechazado un beneficiario

End ticket SSIS-252

---

src/composables/getSelect.ts
src/pages/methodologist/reviews/chronograms/Index.vue
src/pages/reviewfichas/Index.vue
src/pages/subdirector/visit/Form.vue
src/pages/user/Form.vue
src/pages/user/FormEdit.vue

cargar asistentes /auxiliar administrativo en vista de crear usuario

SSIS-289 cargar asistentes al crear metodologo

---

src/components/Crud.vue
src/composables/getMonitorByMunicipality.ts
src/pages/coordinators/Index.vue
src/pages/methodologist/Form.vue
src/pages/user/UsersViewer.vue
src/router/index.ts
src/services/coordinatorVisitServices.ts
src/stores/side-menu.ts

ajusted de acciones de usuarios y otros varios

Diego ortiz

---

src/components/Crud.vue
src/pages/forms/FormEdit.vue
src/pages/forms/View.vue
src/pages/reviewfichas/Form.vue
src/pages/reviewfichas/Index.vue
src/services/beneficiary/beneficiary.ts
src/stores/side-menu.ts

* Ajustes de acciones en el CRUD
* Añadida la pantalla de edicion de beneficiarios como dinámica
* Añadidos botones
* Eliminacion de pantalla reviewForm y comprobación desde el router *cambiado el componente a mostrar de form a view
*Colocado user en monitor que tenia icono de actividad *Conectada la ruta del servicio

Ajustes en Módulo Beneficiarios

---

src/helpers/downloadFile.ts
src/pages/forms/View.vue
src/services/beneficiary/beneficiary.ts

en asistente administrativo con fichas en estado aprobado unicamente.

terminada funcion descarga de beneficiarios AD- APR unicamente

---

auto-imports.d.ts
src/components/Crud.vue
src/pages/event_supports/Form.vue
src/pages/event_supports/FormEdit.vue
src/pages/event_supports/Index.vue
src/pages/reviewfichas/Index.vue
src/router/index.ts
src/services/eventSupportsService.ts
src/stores/side-menu.ts

Agregar y listar soporte de eventos

SSIS 361,371

---

src/assets/css/_tailwind.css
src/components/Crud.vue
src/pages/chronogram/Form.vue
src/pages/event_supports/FormView.vue
src/pages/event_supports/Index.vue
src/pages/methodologist/Form.vue
src/pages/psychosocial/transversal-activity/Edit.vue
src/pages/psychosocial/visit/FormEdit.vue
src/pages/psychosocial/visits/index.vue
src/pages/psychosocial_coordinator/reviews/index.vue
src/pages/reviewfichas/Review.vue
src/pages/user/UsersViewer.vue
src/router/index.ts
src/stores/side-menu.ts

Avances generales, aprobado por Alejandro en meet.

SSIS 393,395,399,400,401,402,404,405,408,409

---

src/pages/methodologist/Edit.vue
src/pages/methodologist/Form.vue
src/pages/subdirector/review/methodologist/Form.vue
src/pages/technical_director/reviews/subdirectorVisitReview.vue
src/pages/technical_subdirector/visit/Form.vue
src/pages/technical_subdirector/visit/FormEdit.vue
src/pages/user/UsersViewer.vue
src/pages/views/Form.vue
src/pages/visit/Form.vue
src/pages/zones/Index.vue

SSIS 412,414,415,417,418

---

src/pages/user/Form.vue
src/pages/user/UsersViewer.vue

Agregar botón de "Crear usuario" en rol admin, y campo "Asistente Auxiliar y Administrativo" al agregar psicosocial

Botón de agregar y campo auxiliar
